app = "toolhouzz-backend"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
```

5. **Commit:** "Added fly.toml for Fly.io deployment"

---

#### File 2: Create `Procfile`

1. **Still on GitHub, click:** "Add file" → "Create new file"

2. **Filename:** `Procfile`

3. **Content:** Just this one line:
```
web: gunicorn app:app --bind 0.0.0.0:$PORT
